export const dummySkills: SkillRecord[] = [
  {
    id: 'skill-1',
    title: 'Write Code',
    slug: 'write-code',
    description: 'Generate production-ready code snippets for common app tasks and debugging workflows.',
    category: 'development',
    tags: ['code', 'programming', 'development'],
    installCommand: 'npm install @skild/write-code',
    createdAt: '2026-09-12T09:00:00.000Z',
    authorClerkId: 'user_123',
    authorEmail: 'alex@example.com',
  },
  {
    id: 'skill-2',
    title: 'Design UI',
    slug: 'design-ui',
    description: 'Create polished design systems, responsive layouts, and accessible interface suggestions.',
    category: 'design',
    tags: ['ui', 'design', 'frontend'],
    installCommand: 'npm install @skild/design-ui',
    createdAt: '2026-09-11T14:15:00.000Z',
    authorClerkId: 'user_456',
    authorEmail: 'sam@example.com',
  },
  {
    id: 'skill-3',
    title: 'Debug Errors',
    slug: 'debug-errors',
    description: 'Analyze stack traces and offer practical fixes for runtime and build-time issues.',
    category: 'debugging',
    tags: ['debug', 'logs', 'fixes'],
    installCommand: 'npm install @skild/debug-errors',
    createdAt: '2026-09-10T11:45:00.000Z',
    authorClerkId: 'user_789',
    authorEmail: 'mila@example.com',
  },
  {
    id: 'skill-4',
    title: 'Optimize Performance',
    slug: 'optimize-performance',
    description: 'Identify bottlenecks and suggest ways to reduce latency, bundle size, and re-renders.',
    category: 'performance',
    tags: ['speed', 'performance', 'optimization'],
    installCommand: 'npm install @skild/optimize-performance',
    createdAt: '2026-09-09T08:20:00.000Z',
    authorClerkId: 'user_321',
    authorEmail: 'noah@example.com',
  },
  {
    id: 'skill-5',
    title: 'Write Tests',
    slug: 'write-tests',
    description: 'Generate reliable unit and integration tests that cover critical user flows.',
    category: 'qa',
    tags: ['testing', 'quality', 'automation'],
    installCommand: 'npm install @skild/write-tests',
    createdAt: '2026-09-08T16:40:00.000Z',
    authorClerkId: 'user_654',
    authorEmail: 'zoe@example.com',
  },
]

export default dummySkills
